"""sync with cinematic frontend

Revision ID: bebb2b082103
Revises: c50257029416
Create Date: 2026-03-25 17:13:46.583257

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bebb2b082103'
down_revision = 'c50257029416'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trips', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subtitle', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('body', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))
        batch_op.drop_column('description')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar_url', sa.String(), nullable=True))

    with op.batch_alter_table('waymarks', schema=None) as batch_op:
        batch_op.drop_column('timestamp_in_video')
        batch_op.drop_column('story')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('waymarks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('story', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('timestamp_in_video', sa.INTEGER(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('avatar_url')

    with op.batch_alter_table('trips', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.TEXT(), nullable=True))
        batch_op.drop_column('status')
        batch_op.drop_column('body')
        batch_op.drop_column('subtitle')

    # ### end Alembic commands ###
